apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "postgres.name" . }}
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
