{{- range .Values.processors }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      initContainers:
      - name: copy-config
        image: busybox
        command: ["sh", "-c", "mkdir -p /.movement && cp /tmp/config/{{ .name }}.json /.movement/config.json"]
        volumeMounts:
          - name: config-volume
            mountPath: /tmp/config
          - name: movement-dir
            mountPath: /.movement
      containers:
        - name: {{ .name }}
          image: {{ $.Values.image.repository }}:{{ $.Values.image.tag }}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          env:
            - name: DOT_MOVEMENT_PATH
              value: "/.movement"
          volumeMounts:
            - name: movement-dir
              mountPath: /.movement
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "processor.fullname" $ }}-config
        - name: movement-dir
          emptyDir: {}
{{- end }}
